spring:
  profiles:
    active:
    - dev 
---
spring:
  profiles: dev #开发环境
  application:
    name: onlineservercloud-config-dev
---
spring:
  profiles: test #开发环境
  application:
    name: onlineservercloud-config-test
#使用utf-8保存格式