spring:
  profiles:
    active:
    - dev 
---
server:
  port: 8201
 
spring:
  profiles: dev
  application:
    name: onlineservicecloud-config-client12345
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
---
server:
  port: 8202
 
spring:
  profiles: test
  application:
    name: onlineservicecloud-config-client
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#使用utf-8保存格式
