spring:
  profiles:
    active:
    - dev 
---
server:
  port: 8201
 
spring:
  profiles: dev
  application:
    name: onlineservicecloud-config-client12345789
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      
      
# rabbitmq:
#   host: 192.168.183.139
#   port: 5672
#   username: xuyihong
#   password: 123456



#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"      
---
server:
  port: 8204
 
spring:
  profiles: test
  application:
    name: onlineservicecloud-config-client
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      
 rabbitmq:
  host: 192.168.183.139
  port: 5672
  username: xuyihong
  password: 123456



#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"     
#使用utf-8保存格式
