spring:
  profiles:
    active:
    - dev 
---
server:
  port: 8001


spring:
  profiles: dev
  application:
    name: microservicecloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis-plus:
  mapper-locations:  classpath:mapper/**/*.xml
  type-aliases-package: com.xu.microservicecloudapi.*.model


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: microservicecloud-dept8001



info:
  app.name: springcloud测试
  company.name: www.xuyihong.com
  build.artifactId: "@project.description@"
  build.version: "@project.modelVersion@"
---
server:
  port: 8001


spring:
  profiles: test
  application:
    name: microservicecloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis-plus:
  mapper-locations:  classpath:mapper/**/*.xml
  type-aliases-package: com.xu.microservicecloudapi.*.model


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: microservicecloud-dept8001



info:
  app.name: springcloud测试
  company.name: www.xuyihong.com
  build.artifactId: "@project.description@"
  build.version: "@project.modelVersion@"
#使用utf-8保存格式
