spring:
  profiles:
    active:
    - dev 
---
server:
  port: 8202
 
spring:
  profiles: dev
  application:
    name: onlineservicecloud-config-clientfdffd12
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

rabbitmq: #rabbitmq相关配置，15672是web管理端口，5672是mq访问端口
  port: 5672
  host: 192.168.183.139
  username: xuyihong
  password: 123456
      
 #暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"     
      
---
server:
  port: 8203
 
spring:
  profiles: test
  application:
    name: onlineservicecloud-config-client
    
rabbitmq: #rabbitmq相关配置，15672是web管理端口，5672是mq访问端口
  port: 5672
  host: 192.168.183.139
  username: xuyihong
  password: 123456
      
 #暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"     
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#使用utf-8保存格式
